import ImageOne from '../../images/bg.jpg';
import ImageTwo from '../../images/wedding2ink.jpg';
import ImageThree from '../../images/nailsservice.jpg';
import ImageFour from '../../images/wimpernlifting.jpg';

export const homeObjOne = {
    id: "about",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'etwas mehr über mich',
    headline: 'Willkommen im Kosmetikstudio Kamin',
    description: 'Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam',
    buttonLabel: 'Mehr Erfahren',
    imgStart: false,
    img: ImageOne,
    alt: "Welcome",
    dark: true,
    primary: true,
    darkText: false,
    ButtonPath: "infocontentone",
    dataAos: "zoom-in-up",
    dataAosTwo: "zoom-in-left",
    dataAosImg: "flip-up"
}
export const homeObjTwo = {
    id: "classic",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Classic',
    headline: 'Enzympeeling & Skin-Scrubber',
    description: 'Peelt und entfernt Hauntunreinheiten, Brauenkorrektur, Maske und Abschlusspflege',
    price: '40.00 €',
    buttonLabel: 'zum Trailer',
    imgStart: true,
    img: ImageTwo,
    alt: "Welcome",
    dark: true,
    primary: true,
    darkText: true,
    ButtonPath: "infocontenttwo",
    dataAos: "zoom-in",
    dataAosTwo: "zoom-in-right",
    dataAosImg: "flip-down"
}
export const homeObjThree = {
    id: "clean",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Clean',
    headline: 'AUA-Enzyme Peeling & Skin-Scrubber',
    description: 'Peelt und entfernt Hautunreinheiten, Brauenkorrektur, Ausreinigung, Ampulle, Maske und Abschlusspflege',
    price: '46.00 €',
    buttonLabel: 'zum Trailer',
    imgStart: false,
    img: ImageThree,
    alt: "Welcome",
    dark: true,
    primary: true,
    darkText: false,
    ButtonPath: "infocontentthree",
}
export const homeObjFour = {
    id: "comfort",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Comfort',
    headline: 'Behandlung von Gesicht, Hals und Dekolleté',
    description: 'Enzympeeling & Skin-Scrubber, Peelt und entfernt Hautunreinheiten, Brauenkorrektur eine Ausreinigung, Ampulle, Massage, Vliesmaske, Ultraschall und anschließend die Abschlusspflege',
    price: '65.00 €',
    buttonLabel: 'zum Trailer',
    imgStart: true,
    img: ImageFour,
    alt: "Welcome",
    dark: true,
    primary: true,
    darkText: true,
    ButtonPath: "infocontentfour",
}
export const homeObjFive = {
    id: "exklusiv",
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Exklusiv',
    headline: 'Mit Botoxähnlichen Wirkstoffen',
    description: 'Enzympeeling & Skin-Scrubber (peelt und entfernt Hautunreinheiten), Brauenkorrektur, Ampulle Relax-Peel-Off Maske, und anschließend die Abschlusspflege',
    price: '48.00 €',
    buttonLabel: 'zum Trailer',
    imgStart: false,
    img: ImageThree,
    alt: "Welcome",
    dark: true,
    primary: true,
    darkText: false,
    ButtonPath: "infocontentthree",
}
export const homeObjSix = {
    id: "diamant",
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Diamant',
    headline: 'Microdermabrasion',
    description: 'Kontrolliertes abschleifen der Hornschicht, Fältchen und Unebenheiten werden gemindert',
    price: '51.00 €',
    buttonLabel: 'zum Trailer',
    imgStart: true,
    img: ImageThree,
    alt: "Welcome",
    dark: true,
    primary: false,
    darkText: true,
    ButtonPath: "infocontentthree",
}